sudo: required
jdk:
  - openjdk8
before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq
language: scala
# this is necessary because otherwise travis runs gradlew assemble before out tasks
# and if that is run, checkScalaFmtAll won't work
install:
  - true
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.cache
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
git:
  depth: false
jobs:
  include:
    - stage: "compile"
      name: "Compile code and tests"
      script: ci/reporting-pr-failure -- sbt +test:compile
    - stage: "scalafmt"
      name: "Check Scalafmt"
      script: ci/reporting-pr-failure -- sbt scalafmtCheck
    - stage: "check unused (scalafix)"
      name: "Check unused"
      script: ci/reporting-pr-failure --description "Unused imports / scalafix" -- sbt "scalafix --check"
    - state: "Run tests"
      name: "Run tests"
      script: ci/reporting-pr-failure --description "Running tests for all Scala versions" -- sbt +test
